name: EAS Build and Submit - Testflight

on:
  push:
    branches:
      - dev

jobs:
  build-and-submit-ios-dev:
    name: Build and submit iOS (Dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Bump version (Dev)
        run: node scripts/bump-version.js dev

      - name: Commit and push version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app.config.js
          git commit -m "Bump version for dev build"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/dearflow-inc/flora-mobile.git HEAD:${{ github.ref }}

      - name: Build iOS app (Dev)
        run: eas build --platform ios --profile testflight --non-interactive

      - name: Submit iOS app (Dev)
        run: eas submit --platform ios --profile testflight --non-interactive

  build-and-submit-android-dev:
    name: Build and submit Android (Dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Bump version (Dev)
        run: node scripts/bump-version.js dev

      - name: Commit and push version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app.config.js
          git commit -m "Bump version for dev build"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/dearflow-inc/flora-mobile.git HEAD:${{ github.ref }}

      - name: Build Android app (Dev)
        run: eas build --platform android --profile testflight --non-interactive

      - name: Submit Android app (Dev)
        run: eas submit --platform android --profile testflight --non-interactive
