name: EAS Build and Submit - Production

on:
  push:
    branches:
      - main

jobs:
  build-and-submit-ios:
    name: Build and submit iOS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Bump version (Production)
        run: node scripts/bump-version.js production

      - name: Commit and push version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app.config.js
          git commit -m "Bump version for production build"
          git push

      - name: Build iOS app
        run: eas build --platform ios --profile production --non-interactive

      - name: Submit iOS app
        run: eas submit --platform ios --profile production --non-interactive

  build-and-submit-android:
    name: Build and submit Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Bump version (Production)
        run: node scripts/bump-version.js production

      - name: Commit and push version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app.config.js
          git commit -m "Bump version for production build"
          git push

      - name: Build Android app
        run: eas build --platform android --profile production --non-interactive

      - name: Submit Android app
        run: eas submit --platform android --profile production --non-interactive
